openapi: 3.0.0
info:
  title: LLM-ARTIFACT
  version: 1.0.0
servers:
  - url: http://{{base-artifact-url}}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
paths:
  /health:
    get:
      tags:
        - default
      summary: health
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: number
          example: >-
            eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJ7XCJ0ZW5hbnROYW1lXCI6XCJzYXJhdmFuYW4ubUBwdXJwbGVzbGF0ZS5pblwiLFwiYXBwTmFtZVwiOlwiV2F5SVFcIixcImFwcElkXCI6NSxcImltYWdlVXJsXCI6XCJcIixcInRlbmFudElkXCI6NTcsXCJuYW1lXCI6XCJIYXJpIFByYXNhdGggVCAxMjNcIixcInNvY2lhbFJlZ1wiOnRydWUsXCJ0ZW5hbnRMaXN0XCI6W3tcInRlbmFudE5hbWVcIjpcInNhcmF2YW5hbi5tQHB1cnBsZXNsYXRlLmluXCIsXCJpc1RlbmFudE93bmVyXCI6ZmFsc2UsXCJ0ZW5hbnRJZFwiOjU3fV0sXCJlbWFpbElkXCI6XCJoYXJpcHJhc2F0aC50QHB1cnBsZXNsYXRlLmluXCIsXCJnaGxcIjp7XCJjb21wYW55SWRcIjpcIlJwazVPeTNycUs4TFRUb2hScktiXCIsXCJyb2xlXCI6XCJhY2NvdW50IGFkbWluXCIsXCJsb2NhdGlvbklkXCI6XCJSSmZxT21SbFdRek1jVUJoa1lDNlwiLFwidXNlcklkXCI6XCIzblRpTDA1SDFFbUk3a1o1UnY0YVwifSxcIm1vYmlsZU5vXCI6XCIrOTE4NzU0NzIyOTAzXCIsXCJ1c2VySWRcIjoxMjB9IiwiZXhwIjoxNzQ5NzA4NTczLCJpc3MiOiIyVk5pQkNEUXZiQ2RiQWI0U3JodVJCdGlhZ21YWHlaUCJ9.80AsxuZg5OqFof5Au0g7hjvh0qMtfGgqkhzn-6u_pXw
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Fri, 30 May 2025 04:53:19 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            access-control-allow-headers:
              schema:
                type: string
                example: X-Requested-With
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '15'
            vary:
              schema:
                type: string
                example: Origin
            Access-Control-Allow-Credentials:
              schema:
                type: boolean
                example: 'true'
            X-Kong-Upstream-Latency:
              schema:
                type: integer
                example: '25'
            X-Kong-Proxy-Latency:
              schema:
                type: integer
                example: '127'
            Via:
              schema:
                type: number
                example: kong/3.7.1
            X-Kong-Request-Id:
              schema:
                type: string
                example: 26fb9223e16b496280d3b6334e137171
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=31536000
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            Content-Security-Policy:
              schema:
                type: string
                example: object-src 'none'; form-action 'self'; frame-ancestors 'self';
            Permissions-Policy:
              schema:
                type: string
                example: >-
                  accelerometer=(), ambient-light-sensor=(), autoplay=(),
                  battery=(), camera=(), cross-origin-isolated=(),
                  display-capture=(), document-domain=(), encrypted-media=(),
                  execution-while-not-rendered=(),
                  execution-while-out-of-viewport=(), fullscreen=(),
                  geolocation=(), gyroscope=(),hid=(), idle-detection=(),
                  magnetometer=(), microphone=(), midi=(),
                  navigation-override=(), payment=(), picture-in-picture=(),
                  publickey-credentials-get=(), screen-wake-lock=(), serial=(),
                  usb=(), web-share=(), xr-spatial-tracking=()
            Content-Encoding:
              schema:
                type: string
                example: br
          content:
            application/json:
              schema:
                type: object
              example:
                status: success
                displayMessage: Artifact service is up and running
                internalErrorMessage: ''
  /appId:
    get:
      tags:
        - default
      summary: appid
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: number
          example: >-
            eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJ7XCJ0ZW5hbnROYW1lXCI6XCJzYXJhdmFuYW4ubUBwdXJwbGVzbGF0ZS5pblwiLFwiYXBwTmFtZVwiOlwiV2F5SVFcIixcImFwcElkXCI6NSxcImltYWdlVXJsXCI6XCJcIixcInRlbmFudElkXCI6NTcsXCJuYW1lXCI6XCJIYXJpIFByYXNhdGggVCAxMjNcIixcInNvY2lhbFJlZ1wiOnRydWUsXCJ0ZW5hbnRMaXN0XCI6W3tcInRlbmFudE5hbWVcIjpcInNhcmF2YW5hbi5tQHB1cnBsZXNsYXRlLmluXCIsXCJpc1RlbmFudE93bmVyXCI6ZmFsc2UsXCJ0ZW5hbnRJZFwiOjU3fV0sXCJlbWFpbElkXCI6XCJoYXJpcHJhc2F0aC50QHB1cnBsZXNsYXRlLmluXCIsXCJnaGxcIjp7XCJjb21wYW55SWRcIjpcIlJwazVPeTNycUs4TFRUb2hScktiXCIsXCJyb2xlXCI6XCJhY2NvdW50IGFkbWluXCIsXCJsb2NhdGlvbklkXCI6XCJSSmZxT21SbFdRek1jVUJoa1lDNlwiLFwidXNlcklkXCI6XCIzblRpTDA1SDFFbUk3a1o1UnY0YVwifSxcIm1vYmlsZU5vXCI6XCIrOTE4NzU0NzIyOTAzXCIsXCJ1c2VySWRcIjoxMjB9IiwiZXhwIjoxNzQ5NzA4NTczLCJpc3MiOiIyVk5pQkNEUXZiQ2RiQWI0U3JodVJCdGlhZ21YWHlaUCJ9.80AsxuZg5OqFof5Au0g7hjvh0qMtfGgqkhzn-6u_pXw
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Fri, 30 May 2025 04:55:25 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            access-control-allow-headers:
              schema:
                type: string
                example: X-Requested-With
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '23'
            vary:
              schema:
                type: string
                example: Origin
            Access-Control-Allow-Credentials:
              schema:
                type: boolean
                example: 'true'
            X-Kong-Upstream-Latency:
              schema:
                type: integer
                example: '26'
            X-Kong-Proxy-Latency:
              schema:
                type: integer
                example: '50'
            Via:
              schema:
                type: number
                example: kong/3.7.1
            X-Kong-Request-Id:
              schema:
                type: string
                example: e4c48650274d183bdc1bd961a33aa353
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=31536000
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            Content-Security-Policy:
              schema:
                type: string
                example: object-src 'none'; form-action 'self'; frame-ancestors 'self';
            Permissions-Policy:
              schema:
                type: string
                example: >-
                  accelerometer=(), ambient-light-sensor=(), autoplay=(),
                  battery=(), camera=(), cross-origin-isolated=(),
                  display-capture=(), document-domain=(), encrypted-media=(),
                  execution-while-not-rendered=(),
                  execution-while-out-of-viewport=(), fullscreen=(),
                  geolocation=(), gyroscope=(),hid=(), idle-detection=(),
                  magnetometer=(), microphone=(), midi=(),
                  navigation-override=(), payment=(), picture-in-picture=(),
                  publickey-credentials-get=(), screen-wake-lock=(), serial=(),
                  usb=(), web-share=(), xr-spatial-tracking=()
            Content-Encoding:
              schema:
                type: string
                example: br
          content:
            application/json:
              schema:
                type: object
              example:
                appId: wayiqb2f1c21b96f14fbfab7224a2aefd87
  /sampleQuery/wayiqb2f1c21b96f14fbfab7224a2aefd87:
    get:
      tags:
        - default
      summary: sampleQuery/{appId}
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: string
          example: '{{auth-token}}'
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Fri, 30 May 2025 04:56:54 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            access-control-allow-headers:
              schema:
                type: string
                example: X-Requested-With
            x-envoy-upstream-service-time:
              schema:
                type: integer
                example: '19'
            vary:
              schema:
                type: string
                example: Origin
            Access-Control-Allow-Credentials:
              schema:
                type: boolean
                example: 'true'
            X-Kong-Upstream-Latency:
              schema:
                type: integer
                example: '26'
            X-Kong-Proxy-Latency:
              schema:
                type: integer
                example: '63'
            Via:
              schema:
                type: number
                example: kong/3.7.1
            X-Kong-Request-Id:
              schema:
                type: string
                example: 936ced5daaf42914351b8f25dcc61c55
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=31536000
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            Content-Security-Policy:
              schema:
                type: string
                example: object-src 'none'; form-action 'self'; frame-ancestors 'self';
            Permissions-Policy:
              schema:
                type: string
                example: >-
                  accelerometer=(), ambient-light-sensor=(), autoplay=(),
                  battery=(), camera=(), cross-origin-isolated=(),
                  display-capture=(), document-domain=(), encrypted-media=(),
                  execution-while-not-rendered=(),
                  execution-while-out-of-viewport=(), fullscreen=(),
                  geolocation=(), gyroscope=(),hid=(), idle-detection=(),
                  magnetometer=(), microphone=(), midi=(),
                  navigation-override=(), payment=(), picture-in-picture=(),
                  publickey-credentials-get=(), screen-wake-lock=(), serial=(),
                  usb=(), web-share=(), xr-spatial-tracking=()
            Content-Encoding:
              schema:
                type: string
                example: br
          content:
            application/json:
              schema:
                type: object
              example:
                try_me_questions:
                  - index_id: 1
                    created_at: '2025-01-01T10:05:02.577328+00:00'
                    created_by: Nutcracker
                    created_by_email: ''
                    is_system_generated: true
                    question: >-
                      Show me houses with 3+ bedrooms, 2 bathrooms, and 1+ car
                      parking in suburbs within Greater Brisbane that have  high
                      economic diversity, and include air conditioning and
                      built-in wardrobes.
                    description: null
                    last_updated_at: null
                    last_updated_by: null
                    last_updated_by_email: null
                    original_question: >-
                      Show me houses with 3+ bedrooms, 2 bathrooms, and 1+ car
                      parking in suburbs within Greater Brisbane that have  high
                      economic diversity, and include air conditioning and
                      built-in wardrobes.
                    is_deleted: false
                  - index_id: 2
                    created_at: '2025-01-01T10:05:02.577431+00:00'
                    created_by: Nutcracker
                    created_by_email: ''
                    is_system_generated: true
                    question: >-
                      One of my customer is looking to purchase a property in
                      Paddington. Can you create a proposal and send email
                      including a property brief
                    description: null
                    last_updated_at: null
                    last_updated_by: null
                    last_updated_by_email: null
                    original_question: >-
                      One of my customer is looking to purchase a property in
                      Paddington. Can you create a proposal and send email
                      including a property brief
                    is_deleted: false
                  - index_id: 3
                    created_at: '2025-01-01T10:05:02.577470+00:00'
                    created_by: Nutcracker
                    created_by_email: ''
                    is_system_generated: true
                    question: >-
                      What are the public transportation options available in
                      Parramatta, including train stations and bus services?
                    description: null
                    last_updated_at: null
                    last_updated_by: null
                    last_updated_by_email: null
                    original_question: >-
                      What are the public transportation options available in
                      Parramatta, including train stations and bus services?
                    is_deleted: false
                  - index_id: 4
                    created_at: '2025-01-01T10:05:02.577470+00:00'
                    created_by: Nutcracker
                    created_by_email: ''
                    is_system_generated: true
                    question: >-
                      We're looking to downsize to a 2-bedroom apartment in a
                      walkable suburb of Canberra, ACT. We'd like property with
                      a balcony and secure parking. Our budget is $600,000. We
                      would like to include surrounding suburbs as well within
                      40km radius
                    description: null
                    last_updated_at: null
                    last_updated_by: null
                    last_updated_by_email: null
                    original_question: >-
                      We're looking to downsize to a 2-bedroom apartment in a
                      walkable suburb of Canberra, ACT. We'd like property with
                      a balcony and secure parking. Our budget is $600,000. We
                      would like to include surrounding suburbs as well within
                      40km radius
                    is_deleted: false
                  - index_id: 5
                    created_at: '2025-01-01T10:05:02.577470+00:00'
                    created_by: Nutcracker
                    created_by_email: ''
                    is_system_generated: true
                    question: >-
                      What are the eligibility criteria to obtain an estate
                      agent's license in Victoria?
                    description: null
                    last_updated_at: null
                    last_updated_by: null
                    last_updated_by_email: null
                    original_question: >-
                      What are the eligibility criteria to obtain an estate
                      agent's license in Victoria?
                    is_deleted: false
  /collection:
    post:
      tags:
        - default
      summary: collection
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                utterance: string
                collectionName: string
                appId: string
                userId:
                  - string
                collectionData:
                  - queryConversationId: string
                    dialogId: string
                    shortlist_collections:
                      - wq_row_id: 0
                        propertytype: string
                        state: string
                        bathrooms: 0
                        bedrooms: 0
                        carspaces: 0
                        streetnumber: string
                        street: string
                        area: string
                        suburb: string
                        postcode: string
                        landareasqm: 0
                        region: string
                        latitude: 0
                        longitude: 0
                        address: string
                        postedon: '2025-05-30T04:49:19.235Z'
                        inspecton: '2025-05-30T04:49:19.235Z'
                        propertyimages: string
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: string
          example: '{{auth-token}}'
      responses:
        undefined:
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                shortlistResponse:
                  status: success
                  message: >-
                    The selected properties have been successfully added to the
                    string
    get:
      tags:
        - default
      summary: collection
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: string
          example: '{{auth-token}}'
        - name: collectionName
          in: header
          schema:
            type: string
          example: coll_20250530060549
        - name: userId
          in: header
          schema:
            type: integer
          example: '288'
      responses:
        undefined:
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                shortlistCollection:
                  status: string
                  data:
                    - _id: string
                      utterance: string
                      collectionName: string
                      appId: string
                      userId:
                        - string
                      propertyIds:
                        - 0
                      collectionImage: string
                      isDeleted: true
                      createdOn: '2025-05-30T05:11:44.509Z'
                      updatedOn: '2025-05-30T05:11:44.509Z'
                      collectionId: string
                      proposalCount: 0
                      collectionData:
                        - queryConversationId: string
                          dialogId: string
                          shortlist_collections:
                            - wq_row_id: 0
                              typical_price: 0
                              min_price: 0
                              max_price: 0
                              propertytype: string
                              state: string
                              bathrooms: 0
                              bedrooms: 0
                              carspaces: 0
                              streetnumber: string
                              street: string
                              area: string
                              suburb: string
                              postcode: string
                              region: string
                              latitude: 0
                              longitude: 0
                              address: string
                              postedon: '2025-05-30T05:11:44.509Z'
                              inspecton: string
                              propertyimages: string
    put:
      tags:
        - default
      summary: collection
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                utterance: string
                collectionName: string
                appId: string
                userId:
                  - string
                collectionId: string
                collectionData:
                  - {}
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: string
          example: '{{auth-token}}'
      responses:
        undefined:
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                shortlistResponse:
                  status: string
                  message: string
    delete:
      tags:
        - default
      summary: collection
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: number
          example: >-
            eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJ7XCJ0ZW5hbnROYW1lXCI6XCJzYXJhdmFuYW4ubUBwdXJwbGVzbGF0ZS5pblwiLFwiYXBwTmFtZVwiOlwiV2F5SVFcIixcImFwcElkXCI6NSxcImltYWdlVXJsXCI6XCJcIixcInRlbmFudElkXCI6NTcsXCJuYW1lXCI6XCJIYXJpIFByYXNhdGggVCAxMjNcIixcInNvY2lhbFJlZ1wiOnRydWUsXCJ0ZW5hbnRMaXN0XCI6W3tcInRlbmFudE5hbWVcIjpcInNhcmF2YW5hbi5tQHB1cnBsZXNsYXRlLmluXCIsXCJpc1RlbmFudE93bmVyXCI6ZmFsc2UsXCJ0ZW5hbnRJZFwiOjU3fV0sXCJlbWFpbElkXCI6XCJoYXJpcHJhc2F0aC50QHB1cnBsZXNsYXRlLmluXCIsXCJnaGxcIjp7XCJjb21wYW55SWRcIjpcIlJwazVPeTNycUs4TFRUb2hScktiXCIsXCJyb2xlXCI6XCJhY2NvdW50IGFkbWluXCIsXCJsb2NhdGlvbklkXCI6XCJSSmZxT21SbFdRek1jVUJoa1lDNlwiLFwidXNlcklkXCI6XCIzblRpTDA1SDFFbUk3a1o1UnY0YVwifSxcIm1vYmlsZU5vXCI6XCIrOTE4NzU0NzIyOTAzXCIsXCJ1c2VySWRcIjoxMjB9IiwiZXhwIjoxNzQ5NzA4NTczLCJpc3MiOiIyVk5pQkNEUXZiQ2RiQWI0U3JodVJCdGlhZ21YWHlaUCJ9.80AsxuZg5OqFof5Au0g7hjvh0qMtfGgqkhzn-6u_pXw
        - name: collectionName
          in: header
          schema:
            type: string
        - name: userId
          in: header
          schema:
            type: string
      responses:
        undefined:
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                collectionDeleteResponse:
                  status: string
                  message: string
  /collection/search:
    post:
      tags:
        - default
      summary: collection/search
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                page_limit: 50
                page_no: 1
                search_term: string
                date_filter: null
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: string
          example: '{{auth-token}}'
      responses:
        undefined:
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                collectionList:
                  - utterance: string
                    collectionName: string
                    appId: string
                    userId: string
                    propertyIds:
                      - 0
                    collectionImage: string
                    isDeleted: true
                    createdOn: '2025-05-30T05:22:31.773Z'
                    updatedOn: '2025-05-30T05:22:31.773Z'
                    collectionId: string
                    lastUpdatedTime: '2025-05-30T05:22:31.773Z'
                totalCollectionCount: 1
                reachedEnd: true
  /proposal:
    post:
      tags:
        - default
      summary: proposal
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                utterance: string
                collectionName: string
                appId: string
                userId:
                  - string
                collectionData:
                  - queryConversationId: string
                    dialogId: string
                    shortlist_collections:
                      - wq_row_id: 0
                        propertytype: string
                        state: string
                        bathrooms: 0
                        bedrooms: 0
                        carspaces: 0
                        streetnumber: string
                        street: string
                        area: string
                        suburb: string
                        postcode: string
                        landareasqm: 0
                        region: string
                        latitude: 0
                        longitude: 0
                        address: string
                        postedon: '2025-05-30T05:30:02.458Z'
                        inspecton: '2025-05-30T05:30:02.458Z'
                        propertyimages: string
                emails:
                  - user@example.com
                createdBy: string
                authToken: string
                token: string
                apiKey: string
                proposalName: string
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: string
          example: '{{auth-token}}'
      responses:
        undefined:
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                status: success
                message: Your proposal is being processed!
                proposalId: c34c34c1-3034-44e5-85f3-bf40ef112ee9
    get:
      tags:
        - default
      summary: proposal
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: string
          example: '{{auth-token}}'
        - name: collectionname
          in: header
          schema:
            type: string
      responses:
        undefined:
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                shortlistCollection:
                  status: string
                  data:
                    - _id: string
                      utterance: string
                      collectionName: string
                      appId: string
                      userId:
                        - string
                      propertyIds:
                        - 0
                      collectionImage: string
                      isDeleted: true
                      createdOn: '2025-05-30T06:07:20.570Z'
                      updatedOn: '2025-05-30T06:07:20.570Z'
                      collectionId: string
                      proposalCount: 0
                      collectionData:
                        - queryConversationId: string
                          dialogId: string
                          shortlist_collections:
                            - wq_row_id: 0
                              typical_price: 0
                              min_price: 0
                              max_price: 0
                              propertytype: string
                              state: string
                              bathrooms: 0
                              bedrooms: 0
                              carspaces: 0
                              streetnumber: string
                              street: string
                              area: string
                              suburb: string
                              postcode: string
                              region: string
                              latitude: 0
                              longitude: 0
                              address: string
                              postedon: '2025-05-30T06:07:20.570Z'
                              inspecton: string
                              propertyimages: string
    put:
      tags:
        - default
      summary: proposal
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                proposalId: string
                proposalName: string
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: string
          example: '{{auth-token}}'
      responses:
        undefined:
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                proposalResponse:
                  status: string
                  message: string
    delete:
      tags:
        - default
      summary: proposal
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: string
          example: '{{auth-token}}'
        - name: proposalId
          in: header
          schema:
            type: string
      responses:
        undefined:
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                proposalDeleteResponse:
                  status: string
                  message: string
  /proposal/preview:
    post:
      tags:
        - default
      summary: proposal /preview
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                utterance: string
                collectionName: string
                appId: string
                userId:
                  - string
                type: string
                collectionData:
                  - queryConversationId: string
                    dialogId: string
                    shortlist_collections:
                      - wq_row_id: 0
                        propertytype: string
                        state: string
                        bathrooms: 0
                        bedrooms: 0
                        carspaces: 0
                        streetnumber: string
                        street: string
                        area: string
                        suburb: string
                        postcode: string
                        landareasqm: 0
                        region: string
                        latitude: 0
                        longitude: 0
                        address: string
                        postedon: '2025-05-30T06:22:00.012Z'
                        inspecton: '2025-05-30T06:22:00.012Z'
                        propertyimages: string
                emails:
                  - user@example.com
                createdBy: string
                authToken: string
                token: string
                apiKey: string
                proposalName: string
      security:
        - noauthAuth: []
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: auth-token
          in: header
          schema:
            type: string
          example: '{{auth-token}}'
      responses:
        undefined:
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                type: object
              example:
                status: success
                message: Your proposal is being processed!
                proposalId: c34c34c1-3034-44e5-85f3-bf40ef112ee9
